version: "3.7"
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
      SPRING_RABBITMQ_HOST: rabbit
    #    volumes:
    #      - ./db-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      - 5673:5673